# Generated by Django 3.1.3 on 2021-04-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ano_início_projeto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='duração_projeto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='mês_início_projeto',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
