# Generated by Django 2.0.3 on 2021-04-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210419_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='alocação_mensal',
            new_name='projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='ano_início_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='duração_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='função_colaborador',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='mês_início_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='nome_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='status_projeto',
        ),
    ]
