# Generated by Django 2.0.3 on 2021-04-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210420_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='registro',
            new_name='alocação_mensal',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ano_início_projeto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='colaborador',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='projeto',
            name='duração_projeto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='função_colaborador',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='projeto',
            name='mês_início_projeto',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='projeto',
            name='nome_cliente',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='projeto',
            name='nome_projeto',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status_projeto',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
