# Generated by Django 2.0.3 on 2021-04-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210421_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='teste',
        ),
    ]
