# Generated by Django 2.0.3 on 2021-04-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_projeto_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='resumo',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
