# Generated by Django 3.1.3 on 2021-05-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210506_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='chave_matricula',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
